#!/usr/bin/env bash

clear

# Check if user is root
if [ $(id -u) != "0" ]; then
  echo "Error: You must be root to run this script."
  exit 1
fi

######################################################################################

echo "================================================================================"
echo "host-only ip set"
echo "================================================================================"

echo "DEVICE=enp0s8
ONBOOT=yes
BOOTPROTO=static
IPADDR0=192.168.56.200" > /etc/sysconfig/network-scripts/ifcfg-enp0s8

systemctl restart network

echo "set ok"

read VAR

######################################################################################

echo "================================================================================"
echo "selinux off"
echo "================================================================================"


# Disable SeLinux
if [ -s /etc/selinux/config ]; then
  sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
  setenforce 0
fi

echo "set ok"

read VAR

######################################################################################

echo "================================================================================"
echo "change yum repo"
echo "================================================================================"

# http://mirrors.163.com/.help/centos.html
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
curl http://mirrors.163.com/.help/CentOS7-Base-163.repo -o /etc/yum.repos.d/CentOS7-Base-163.repo


yum clean all
yum makecache

echo "set ok"

read VAR

######################################################################################


echo "================================================================================"
echo "share folder"
echo "================================================================================"


# 安装需要的库
yum -y install kernel-devel bzip2 gcc


#挂载 增强工具
mkdir /mnt/cdrom
mount /dev/cdrom /mnt/cdrom

echo "================================================================================"
echo "You need mount VBoxLinuxAdditions"
echo "================================================================================"

read VAR

#安装 增强工具
/mnt/cdrom/VBoxLinuxAdditions.run

#创建共享目录
mkdir /home/winshare

echo "================================================================================"
echo "You need mount VBOX: winshare"
echo "================================================================================"

read VAR

#创建服务文件
echo "[Unit]
Description=home winshare mount
[Mount]
What=winshare
Where=/home/winshare
Type=vboxsf
Options=defaults
[Install]
WantedBy=multi-user.target" > /usr/lib/systemd/system/home-winshare.mount


# 注册服务-设为自动启动
systemctl enable home-winshare.mount
systemctl start home-winshare.mount


echo "set ok"

read VAR

######################################################################################

echo "================================================================================"
echo "update kernel"
echo "================================================================================"

# kenerl update (share folder) ** need for reboot 
yum -y update kernel

echo "set ok"

read VAR

######################################################################################

echo "================================================================================"
echo "You need reboot system"
echo "================================================================================"

exit 0
