#!/usr/bin/env bash

clear

# Check if user is root
if [ $(id -u) != "0" ]; then
  echo "Error: You must be root to run this script."
  exit 1
fi

echo "================================================================================"
echo "share folder"
echo "================================================================================"

yum -y install kernel-devel bzip2 gcc

echo "You need mount VBoxLinuxAdditions"
echo "press enter to continue"

read VAR

mkdir /mnt/cdrom
mount /dev/cdrom /mnt/cdrom

/mnt/cdrom/VBoxLinuxAdditions.run

mkdir /home/public

echo "You need mount VBOX: public"
echo "press enter to continue"

read VAR

#创建服务文件
echo "[Unit]
Description=home winshare mount
[Mount]
What=winshare
Where=/home/winshare
Type=vboxsf
Options=defaults
[Install]
WantedBy=multi-user.target" > /usr/lib/systemd/system/home-winshare.mount


# 注册服务-设为自动启动
systemctl enable home-winshare.mount
systemctl start home-winshare.mount
